spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bcsd?serverTimezone=Asia/Seoul
    username: root
    password: mypass123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      logging:
        level:
          org.springframework.security: DEBUG
      hibernate:
        show_sql: true  # sql 쿼리를 보여줌
        format_sql: true
        use_sql_comments: true  # sql 쿼리의 추가정보를 보여즘
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
